// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCS2Am1PnieMUja9Bwa-Z4_ShLfemBKg_k',
    appId: '1:636624887085:web:64b1201d43b8180f3307a4',
    messagingSenderId: '636624887085',
    projectId: 'fcmexampleandroid-7bc9a',
    authDomain: 'fcmexampleandroid-7bc9a.firebaseapp.com',
    databaseURL: 'https://fcmexampleandroid-7bc9a.firebaseio.com',
    storageBucket: 'fcmexampleandroid-7bc9a.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCrkb--ffYEffPPXS9BHblNol5gDQhE1r0',
    appId: '1:636624887085:android:9e83219ee11fef123307a4',
    messagingSenderId: '636624887085',
    projectId: 'fcmexampleandroid-7bc9a',
    databaseURL: 'https://fcmexampleandroid-7bc9a.firebaseio.com',
    storageBucket: 'fcmexampleandroid-7bc9a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCzb5-hdo7ZWt5s3eIwYV0Foii9Li548vE',
    appId: '1:636624887085:ios:16880aefd528e36f3307a4',
    messagingSenderId: '636624887085',
    projectId: 'fcmexampleandroid-7bc9a',
    databaseURL: 'https://fcmexampleandroid-7bc9a.firebaseio.com',
    storageBucket: 'fcmexampleandroid-7bc9a.firebasestorage.app',
    iosBundleId: 'com.example.flutterDeveloperAsFinal78518Damini',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCzb5-hdo7ZWt5s3eIwYV0Foii9Li548vE',
    appId: '1:636624887085:ios:16880aefd528e36f3307a4',
    messagingSenderId: '636624887085',
    projectId: 'fcmexampleandroid-7bc9a',
    databaseURL: 'https://fcmexampleandroid-7bc9a.firebaseio.com',
    storageBucket: 'fcmexampleandroid-7bc9a.firebasestorage.app',
    iosBundleId: 'com.example.flutterDeveloperAsFinal78518Damini',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCS2Am1PnieMUja9Bwa-Z4_ShLfemBKg_k',
    appId: '1:636624887085:web:a8929fd6479a2a033307a4',
    messagingSenderId: '636624887085',
    projectId: 'fcmexampleandroid-7bc9a',
    authDomain: 'fcmexampleandroid-7bc9a.firebaseapp.com',
    databaseURL: 'https://fcmexampleandroid-7bc9a.firebaseio.com',
    storageBucket: 'fcmexampleandroid-7bc9a.firebasestorage.app',
  );
}
